bedrockPort: 20126
favIconPath: server-icon.png
hideIpInLogs: true
hideOnConnectionLogs: true
loginMessage: '...Despertando el servidor, vuelvo en un minuto...'
maxPlayers: 20
minecraftAutostart: false
minecraftCommand: java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar
restartDelay: 5000
serverName: Estoy hibernando, conectate para poder despertarme... Atentamente Zeus
serverOnlineMode: false
serverPort: 20126
startMinecraft: true
useBlacklistFiles: false
useWhitelistFile: false
